### PR TITLE
Boards and commissions components

### PR DESCRIPTION
**Pull request by finneganh**
Adds components for boards and commissions members as well as a
sidebar component for boards and commissions info.

#### Fixes [insert bug/issue number]
<br>

#### Changes proposed in this pull request:
*
*

### CODE REVIEW

**Comment by finneganh** [comment]
@jimafisk OK updated the JSON parsing.

I'm curious about the get_variable default. Should that be to a staging instance or prod? How would we handle API keys?

**Comment by finneganh** [comment]
Oh, whoops. Looks like that code got stomped at some point.

Right now it’s defaulting to the staging commissions GraphQL server at commissions.digital-staging.boston.gov. Presumably I need to make that a configuration variable. Should it default to the staging URL? Or production?

**Comment by jimafisk** [comment]
@finneganh I assume you're talking about [line 36](https://github.com/CityOfBoston/boston.gov/pull/1057/commits/48979273e83e6e8c35f794bdc72dc19b510b1adc#diff-ea794c8458be1f101b16bbc7d5eaeab6R36)? Yeah this is something you could use variable set/get for. Is the idea that you want the Drupal staging site to point to the Graphql staging server and the prod to prod?

Variable setting looks something like this: `variable_set('commissions_graphql_server', 'https://commissions.digital-staging.boston.gov/commissions/graphql');` which just saves this value to the variable mysql table. Then you can retrieve it with `variable_get('commissions_graphql_server')`. The tricky part is we're constantly overriding the stg db with the prod db so you'd ultimately get those values. You could always reset them via drush though by doing something like this: `drush vset commissions_graphql_server https://commissions.digital-staging.boston.gov/commissions/graphql`

Sorry if I'm not following your question. If you need an environment specific variable for your Drupal site URL, you could use the global `base_url` to avoid hard coding https://api.drupal.org/api/drupal/developer!globals.php/global/base_url/7.x

**Comment by finneganh** [comment]
@jimafisk Ok. So I think that the default should point to the staging instance of the GraphQL server for people in dev, since we don't need an API key or anything for that. Then Boston.gov staging / prod will have the `variable_set` version that points to the prod GraphQL instance.

Is that everything we need to get this checked in?

**Comment by jimafisk** [comment]
@finneganh makes sense to me. Yes this looks great, merge away!

**Pull request merged**
