### PR TITLE
workbench moderation revert rebased

### PR DESCRIPTION
**Pull request by kdonaldson**
#### Fixes [insert bug/issue number]
* Workbench Moderation does not work as expected
* Timestamps are out of order

#### Changes proposed in this pull request:
* Reverts Workbench Moderation module to 1.4
* Remove Drafty module dependency

### CODE REVIEW

**Comment by jimafisk** [comment]
Fixes https://github.com/CityOfBoston/boston.gov/issues/1096#event-1664351363

**Comment by jimafisk** [comment]
@kdonaldson can you hold off merging for a minute. I'd like to read more into this issue https://www.drupal.org/node/2824607

**Comment by jimafisk** [comment]
It looks like the issue is that the current published version gets a forward revision (copy of the existing published version) to mitigate the security flaw and promote the published version to the top of the moderation list. The community wasn't fond of their revision histories being cluttered in this manner + the UX confusion, so it looks like they wrote patches for the "drafty" module, which is where this underlying bug was introduced. Seems to have been merged into dev in Sept 2017: https://www.drupal.org/project/drafty/issues/2579205#comment-12276016

@kdonaldson have you tried using the dev version of drafty and testing? Looks like we're currently using the release candidate

**Comment by kdonaldson** [comment]
@jimafisk no, the dev version was not tested.  I think we have a couple of options:

1. merge 1.4 revert and test the dev version.  If dev works , upgrade at a later date.
2. merge 1.4 revert and move to D8

What do you want to do?

**Comment by jimafisk** [comment]
I tested with the dev version of drafty, that did **not** seem to resolve the issue on my end. Since you think the security risk is low, I agree that we should revert for now. I think we'll also need an update hook in the profile to disable the drafty module or that will throw errors.

**Pull request merged**
