### PR TITLE
Changes owner of .ssh files in container required by some deployments.

### PR DESCRIPTION
**Pull request by davidrkupton**
#### Fixes [insert bug/issue number]
Adhoc dev environment change

#### Changes proposed in this pull request:
* adds code to change ownership of ssh files in the drupal container.

#### Add @mentions of the person or team responsible for reviewing proposed changes
@finneganh @jimafisk

### CODE REVIEW

**Comment by davidrkupton** [comment]
I have added this small change because the database sync process (`docker exec -t bostongov_drupal_1 ./task.sh -Dbehat.run-server=true build:test`) was failing beacuse these files had ownership by account 1000.  This is a simple fix for that issue,  I tried wildcards to change the whole folder, but that didn't seem to work. There should only ever be one ssh key so while 4 lines is less elegant than 1, I don't think it impacts scale-ability.

**Comment by finneganh** [comment]
I think that `.ssh` directory is typically brought in with a bind mount, so chmoding those I think will have repercussions on your host machine.

**Comment by jimafisk** [comment]
I've noticed this same issue @davidrkupton so thanks for looking into it. I believe @coordt has fixed similar problems through his work on labtest. Corey do you have any insights you can share here? Thanks!

**Comment by finneganh** [comment]
@davidrkupton Can you respond about what this does to `~/.ssh` on the host machine?

Also, please don’t merge PRs that have open questions.

**Pull request merged**
